{% set name = "xmovie" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xmovie-{{ version }}.tar.gz
  sha256: 668f783a0f2a969b4f572bd5908f51fd4c079cd5f5519e87d644b7f56b11ab21

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - cartopy
    - dask-core
    - numpy
    - python >={{ python_min }}
    - xarray

test:
  imports:
    - xmovie
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jbusecke/xmovie
  summary: Simply create beautiful movies from xarray objects
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jbusecke
